part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const PROMO = _Paths.PROMO;
  static const LOGIN = _Paths.LOGIN;
  static const REGISTER = _Paths.REGISTER;
  static const PROFILE = _Paths.PROFILE;
  static const profileView = _Paths.ProfileView;
  static const EXPLORE = _Paths.EXPLORE;
  static const BOOKMARK = _Paths.BOOKMARK;
  static const CATEGORY = _Paths.CATEGORY;
  static const ONBOARDING = _Paths.ONBOARDING;
  static const STARTED = _Paths.STARTED;
  static const POPULAR = _Paths.POPULAR;
  static const MESSAGE = _Paths.MESSAGE;
  static const NOTIFICATION = _Paths.NOTIFICATION;
  static const SERVICEBOOKING = _Paths.SERVICEBOOKING;
  static const bookService = _Paths.BookService;
  static const BOOKUPCOMING = _Paths.BOOKUPCOMING;
  static const BOOKCOMPLETED = _Paths.BOOKCOMPLETED;
  static const BOOKCANCELLED = _Paths.BOOKCANCELLED;
  static const BOOKSUCCESS = _Paths.BOOKSUCCESS;
  static const PAYMENTMETHOD = _Paths.PAYMENTMETHOD;
  static const addCard = _Paths.addCard;
  static const REVIEWSUMMARY = _Paths.REVIEWSUMMARY;
  static const SUCCESSBOOKING = _Paths.SUCCESSBOOKING;
  static const ERECEIPT = _Paths.ERECEIPT;
  static const PRIVACYPOLICY = _Paths.PRIVACYPOLICY;
  static const CONFIRM_ADDRESS = _Paths.CONFIRM_ADDRESS;
  static const servicePage = _Paths.servicePage;
  static const servicePageConfirmation = _Paths.servicePageConfirmation;
  static const LOCATIONINPUT = _Paths.LOCATIONINPUT;
  static const SERVICE = _Paths.SERVICE;
  static const REVIEW = _Paths.REVIEW;
  static const GALLARY = _Paths.GALLARY;
  static const ABOUT = _Paths.ABOUT;
  static const HELP_CENTER_FAQ = _Paths.HELP_CENTER_FAQ;
  static const CONTACT_US = _Paths.CONTACT_US;
  static const HELPWEBVIEW = _Paths.HELPWEBVIEW;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const HOMEMERDEKA = '/homeMerdeka';
  static const PROMO = '/promo';
  static const LOGIN = '/login';
  static const REGISTER = '/register';
  static const PROFILE = '/profile';
  static const ProfileView = '/profile/edit';
  static const EXPLORE = '/explore';
  static const BOOKMARK = '/bookmark';
  static const CATEGORY = '/category';
  static const ONBOARDING = '/onboarding';
  static const STARTED = '/started';
  static const POPULAR = '/popular-service';
  static const MESSAGE = '/message';
  static const NOTIFICATION = '/notification';
  static const SERVICEBOOKING = '/service-booking';
  static const BookService = '/book/service';
  static const BOOKUPCOMING = '/bookupcoming';
  static const BOOKCOMPLETED = '/bookcompleted';
  static const BOOKCANCELLED = '/bookcancelled';
  static const BOOKSUCCESS = '/booksuccess';
  static const PAYMENTMETHOD = '/paymentmethod';
  static const addCard = '/payment/method/card';
  static const REVIEWSUMMARY = '/reviewsummary';
  static const SUCCESSBOOKING = '/successbooking';
  static const ERECEIPT = '/ereceipt';
  static const PRIVACYPOLICY = '/privacypolicy';
  static const CONFIRM_ADDRESS = '/confirm_address';
  static const servicePage = '/service/page';
  static const servicePageConfirmation = '/service/page/confirmation';
  static const LOCATIONINPUT = '/locationinput';
  static const SERVICE = '/service';
  static const REVIEW = '/review';
  static const GALLARY = '/gallary';
  static const ABOUT = '/about';
  static const HELP_CENTER_FAQ = '/help_center_faq';
  static const CONTACT_US = '/contact_us';
  static const HELPWEBVIEW = '/helpwebview';
}
